### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by brianLoomis** [sagikazarmark/crypt#265]
crypt uses hashi's consul/api, which since 1.17 has been under Business Source License (BSL), which is not a recognized open source license.  Are there plans to update crypt to either take up BSL as its license, or get an MIT-compliant license for hashi's component?  We would like to use crypt under MIT license.  Please feel free to reply to brian.loomis@progress.com and delete this issue since it's really a question.  thanks!

**Comment by sagikazarmark** [comment]
@brianLoomis my understanding is that the API package is still licensed under MPL 2.0: https://github.com/hashicorp/consul/blob/main/api/LICENSE

MPL 2.0 is a recognized OSS license and doesn't affect how you use crypt (as far as my understanding of licensing goes).

**Comment by brianLoomis** [comment]
Thank you – I was only looking at the top level BSL, thanks for pointing out the lower level API-specific one.

From: Márk Sági-Kazár ***@***.***>
Date: Wednesday, April 3, 2024 at 6:54 PM
To: sagikazarmark/crypt ***@***.***>
Cc: Brian Loomis ***@***.***>, Mention ***@***.***>
Subject: Re: [sagikazarmark/crypt] license question (Issue #265)

@brianLoomis<https://github.com/brianLoomis> my understanding is that the API package is still licensed under MPL 2.0: https://github.com/hashicorp/consul/blob/main/api/LICENSE

MPL 2.0 is a recognized OSS license and doesn't affect how you use crypt (as far as my understanding of licensing goes).
